name: Upload Frontend dev

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Install & Build
    steps:
      - uses: actions/checkout@v2
      - id: install
        run: npm ci
      - id: build
        run: npm run build
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: dev.speedcal.date
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2' # optional: defaults to us-east-1
          SOURCE_DIR: 'build' # optional: defaults to entire repository
